const jokes = [
    { "id": 1, "joke": "I told my boss I needed a raise. He laughed… I guess he thought I was joking." },
    { "id": 2, "joke": "Why don't graveyards ever get overcrowded? Because people are dying to get in." },
    { "id": 3, "joke": "Marriage is like a horror movie. The only difference is, in horror movies, the monsters are fake." },
    { "id": 4, "joke": "I asked my wallet for money. It laughed at me." },
    { "id": 5, "joke": "They say money can’t buy happiness, but it can buy a jet ski. And have you ever seen anyone sad on a jet ski?" },
    { "id": 6, "joke": "Therapist: ‘What do we say when we feel like this?’ Me: ‘More coffee, less feelings.’" },
    { "id": 7, "joke": "I have an inferiority complex, but it’s not a very good one." },
    { "id": 8, "joke": "They say laughter is the best medicine. That’s why I laugh when people say therapy is expensive." },
    { "id": 9, "joke": "I told my wife she should embrace her mistakes. She hugged me." },
    { "id": 10, "joke": "The bank told me I had an outstanding balance… I said, 'Thank you, I’ve been practicing.'" },
    { "id": 11, "joke": "I named my dog ‘5 Miles’ so I can say I walk 5 miles every day." },
    { "id": 12, "joke": "My ex’s new boyfriend asked me if she was crazy. I said, ‘No, she’s completely sane... on paper.’" },
    { "id": 13, "joke": "Why don’t cannibals eat clowns? Because they taste funny." },
    { "id": 14, "joke": "I asked my crush if she had a boyfriend. She said, ‘Yes, you do now.’ My funeral is next Thursday." },
    { "id": 15, "joke": "Why was the orphan’s phone bill so high? Because he never got any calls from his parents." },
    { "id": 16, "joke": "My love life is like a ghost… nonexistent, but it still haunts me." },
    { "id": 17, "joke": "I have a joke about construction. But I’m still working on it." },
    { "id": 18, "joke": "I asked my teacher if I could retake the test. He said, ‘I’d let you, but I don’t believe in miracles.’" },
    { "id": 19, "joke": "The worst thing about being a night owl? Realizing the world is built for morning people." },
    { "id": 20, "joke": "I’m on a whiskey diet. I’ve lost three days already." },
    { "id": 21, "joke": "Why do hospitals always smell weird? Because they’re full of sick people." },
    { "id": 22, "joke": "I tried to start a bakery, but I just didn’t have the dough." },
    { "id": 23, "joke": "Why do vampires always seem wealthy? Because they don’t waste money on food." },
    { "id": 24, "joke": "They say the best things in life are free. That’s why I don’t have any." },
    { "id": 25, "joke": "If at first you don’t succeed… skydiving is not for you." },
    { "id": 26, "joke": "I told my boss I was quitting for ‘personal reasons.’ The reason? I personally hate this job." },
    { "id": 27, "joke": "I got fired from my job at the bank today. An old lady asked me to check her balance, so I pushed her over." },
    { "id": 28, "joke": "Dark humor is like food. Not everyone gets it." },
    { "id": 29, "joke": "I thought I had Covid. Turns out, I just hate people." },
    { "id": 30, "joke": "I hate funerals. Not only do they cost a fortune, but the guest of honor never even shows up." },
    { "id": 31, "joke": "I tried to buy a camouflage jacket, but I couldn't find one." },
    { "id": 32, "joke": "I used to be a banker… but I lost interest." },
    { "id": 33, "joke": "Why don’t serial killers ever go on vacation? Because they prefer to stay committed." },
    { "id": 34, "joke": "The doctor said I have a rare disease… It's called 'being broke'." },
    { "id": 35, "joke": "I told my friend I was going to be a stand-up comedian. He said, ‘Sit back down.’" },
    { "id": 36, "joke": "Life is like a camera. Focus on the good times and delete the bad ones." },
    { "id": 37, "joke": "My boss asked me why I was late. I told him, ‘Traffic was terrible.’ I work from home." },
    { "id": 38, "joke": "They say the best way to a man’s heart is through his stomach. But a knife works too." },
    { "id": 39, "joke": "I love my job. My co-workers are just jealous because the voices talk to me more." },
    { "id": 40, "joke": "I heard oxygen and magnesium were dating. I was like, ‘O Mg!’" },
    { "id": 41, "joke": "I told my friend I had an addiction. He said, ‘To what?’ I said, ‘Bad decisions.’" },
    { "id": 42, "joke": "I got kicked out of a funeral for saying, ‘At least he doesn’t have to pay taxes anymore.’" },
    { "id": 43, "joke": "My friend told me he’s moving to Switzerland. I asked him why. He said, ‘Well, the flag is a big plus.’" },
    { "id": 44, "joke": "The worst part about being unemployed? You never get fired." },
    { "id": 45, "joke": "My doctor told me I had 24 hours to live. So I asked him, ‘Can I pay my bill tomorrow?’" },
    { "id": 46, "joke": "They say ‘You are what you eat.’ That explains why I’m broke and full of regret." },
    { "id": 47, "joke": "I got my paycheck today. I just wish it wasn’t a joke." },
    { "id": 48, "joke": "Why did the credit card go to therapy? Because it had too many charges." },
    { "id": 49, "joke": "I walked past a cemetery, and a sign said, ‘No trespassing.’ But who’s going to complain?" },
    { "id": 50, "joke": "I told my wife she should embrace her mistakes. So she hugged me." }
];

module.exports = jokes;
